# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 469)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.horizontalLayout.addWidget(self.btnOpenFile)
        self.btnRecognize = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecognize.setObjectName("btnRecognize")
        self.horizontalLayout.addWidget(self.btnRecognize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmbAllAlgo = QtWidgets.QComboBox(self.centralwidget)
        self.cmbAllAlgo.setObjectName("cmbAllAlgo")
        self.cmbAllAlgo.addItem("")
        self.cmbAllAlgo.addItem("")
        self.cmbAllAlgo.addItem("")
        self.cmbAllAlgo.setItemText(2, "")
        self.verticalLayout.addWidget(self.cmbAllAlgo)
        self.txtConfig = QtWidgets.QTextEdit(self.centralwidget)
        self.txtConfig.setObjectName("txtConfig")
        self.verticalLayout.addWidget(self.txtConfig)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.listSelectAlgo = QtWidgets.QListWidget(self.centralwidget)
        self.listSelectAlgo.setObjectName("listSelectAlgo")
        self.horizontalLayout_2.addWidget(self.listSelectAlgo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOpenFile.setText(_translate("MainWindow", "打开文件"))
        self.btnRecognize.setText(_translate("MainWindow", "开始识别"))
        self.cmbAllAlgo.setItemText(0, _translate("MainWindow", "二值化"))
        self.cmbAllAlgo.setItemText(1, _translate("MainWindow", "滤波"))
        self.btnAdd.setText(_translate("MainWindow", ">>"))
