# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ocr_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnOpenFile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenFile.sizePolicy().hasHeightForWidth())
        self.btnOpenFile.setSizePolicy(sizePolicy)
        self.btnOpenFile.setMinimumSize(QtCore.QSize(0, 20))
        self.btnOpenFile.setMaximumSize(QtCore.QSize(16777215, 20))
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.horizontalLayout_2.addWidget(self.btnOpenFile)
        self.btnRecognize = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRecognize.sizePolicy().hasHeightForWidth())
        self.btnRecognize.setSizePolicy(sizePolicy)
        self.btnRecognize.setMinimumSize(QtCore.QSize(0, 20))
        self.btnRecognize.setMaximumSize(QtCore.QSize(16777215, 20))
        self.btnRecognize.setObjectName("btnRecognize")
        self.horizontalLayout_2.addWidget(self.btnRecognize)
        spacerItem = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSrc = QtWidgets.QLabel(self.centralwidget)
        self.lblSrc.setMinimumSize(QtCore.QSize(300, 300))
        self.lblSrc.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSrc.setObjectName("lblSrc")
        self.horizontalLayout.addWidget(self.lblSrc)
        self.lblRecognize = QtWidgets.QLabel(self.centralwidget)
        self.lblRecognize.setMinimumSize(QtCore.QSize(300, 300))
        self.lblRecognize.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRecognize.setObjectName("lblRecognize")
        self.horizontalLayout.addWidget(self.lblRecognize)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOpenFile.setText(_translate("MainWindow", "打开文件"))
        self.btnRecognize.setText(_translate("MainWindow", "识别"))
        self.lblSrc.setText(_translate("MainWindow", "原图像"))
        self.lblRecognize.setText(_translate("MainWindow", "识别后"))
